# Generated by Django 2.2.1 on 2020-09-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('email', models.CharField(max_length=100, verbose_name='Email del cliente')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefono del cliente')),
            ],
        ),
    ]
